### ISSUE TITLE
fib: Move `let current = …` into for-loop?

### ISSUE THREAD

**Issue by regexident** [saintsebastian/learning-rust#1]
Hey Elvina,

Given that `current` is only ever allocated, used and discarded within a single loop iteration you could safely move the declaration into the for-loop and even make it non-`mut`, and drop the explicit type declaration, if you feel like it makes things more readable for you.

Why do I think that this improves the code? Because it makes it clear that the use of `current` is strictly limited to the loop's body and that within the loop's body it is not mutated. Having been moved into the loop body one now only has to reason about `current` within the loop. Before you had to take everything that follows the loop into consideration when trying to figure out the purpose of `let mut current …`.

[fib/src/main.rs](https://github.com/saintsebastian/learning-rust/blob/master/fib/src/main.rs#L8)

**Comment by saintsebastian** [comment]
You are completely correct, since `current` is only needed to hold a value for the duration of the loop.
