### ISSUE TITLE
Maybe add a rust-specific `.gitignore` file?

### ISSUE THREAD

**Issue by regexident** [saintsebastian/learning-rust#2]
A couple of your sub-crates have the `/target/` directory checked in.
Usually this directory is ignored as it contains build artifacts and intermediary files.

[gi](https://github.com/joeblau/gitignore.io) is a great command-line tool to generate `.gitignore` files for particular types of projects:

```bash
$ cd /path/to/learning-rust
$ gi osx rust > .gitignore
$ git commit -a -m "Added gitignore file"
```

Check out [gitignore.io](http://gitignore.io/) to see the available templates to pick from.

When creating your projects via `$ cargo new …` you should actually never have to create a `.gitignore` file yourself manually.

Cargo (currently, this might change in future versions) creates a `.gitignore` file with this content …

```
/target/
**/*.rs.bk
Cargo.lock
```

(Given that those `/target/` directories are already tracked by git in your case you would have to remove them manually.)

**Comment by saintsebastian** [comment]
thanks a bunch, had to add a couple of globs, and did an old `git rm --cached 'git ls-files -i --exclude-from=.gitignore'` trick. But I think I am good now

**Comment by regexident** [comment]
Cool!
